### ISSUE TITLE
Taking interest rate and principle input from the user instead of manually entering

### ISSUE THREAD

**Issue by Pradeepkumarpalanisamy** [Pradeepkumarpalanisamy/Gain-profit-calculator---Compound-Interest#1]
For now, the code requires user to directly edit the line number 10 each time if they want to input new interest rate and principle amount.

The idea is to get the input from users for both interest rate and principle so the prompt appears when the code compiled

>percentage (2, 1000)

**Comment by Pradeepkumar-064** [comment]
Checking if this issue can be assigned to me.
